# Generated by Django 3.0.7 on 2020-08-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futisveikkaus', '0002_luotulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osallistuja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
                ('ottelu_pari', models.CharField(max_length=100)),
                ('veikkaus_koti', models.IntegerField()),
                ('veikkaus_vieras', models.IntegerField()),
                ('veikkaus_yksiristikaksi', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='luotulos',
            name='tulos_yksiristikaksi',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
